services:
  my-app:
    build:
      context: .
      args:
        STUDENT_NAME: "Caesar Eka Nathanael"
        STUDENT_NIM: "0000067638"
    ports:
      - "80:3000"
    environment:
      NODE_ENV: development
